{% set name = "aeolus" %}
{% set version = "24.4.29.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d1e40a9326f6b16ff29c03b03ca3a5915418b68886fba4b17b34dee601d42d56

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - aeolus = aeolus.cli:main

requirements:
  host:
    - python >=3.10
    - pip
    - setuptools >=68
    - setuptools-scm >=8
  run:
    - python >=3.10
    - click >=8.1.7
    - click-default-group >=1.2.4
    - python >=3.10
    - cached-property >=1.5.1
    - scitools-iris >=3.10
    - matplotlib-base >=3.6
    - numpy >=1.24

test:
  imports:
    - aeolus
    - aeolus.calc
    - aeolus.const
    - aeolus.coord
    - aeolus.model
    - aeolus.plot
    - aeolus.subset
  commands:
    - pip check
    - aeolus --help
  requires:
    - pip

about:
  home: https://github.com/exoclim/aeolus
  license: LGPL-3.0-only
  license_family: LGPL
  license_file: LICENSE
  summary: Python library for object-oriented analysis of climate model output.
  dev_url: https://github.com/exoclim/aeolus
  doc_url: https://exoclim.github.io/aeolus

extra:
  recipe-maintainers:
    - dennissergeev
