{% set python_min = '3.10' %}
{% set name = "aeolus" %}
{% set version = "24.11.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d42a23dd8ddbaa2e9a93b3dc522af51154afb36585eb80b5c87d26abcb4d7910

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - aeolus = aeolus.cli:main

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools >=68
    - setuptools-scm >=8
  run:
    - python >={{ python_min }}
    - click >=8.1.7
    - click-default-group >=1.2.4
    - python >={{ python_min }}
    - cached-property >=1.5.1
    - scitools-iris >=3.10
    - matplotlib-base >=3.6
    - numpy !=1.24.3,>=1.21.0

test:
  imports:
    - aeolus
    - aeolus.calc
    - aeolus.const
    - aeolus.coord
    - aeolus.model
    - aeolus.plot
    - aeolus.subset
  commands:
    - pip check
    - aeolus --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/exoclim/aeolus
  license: LGPL-3.0-only
  license_family: LGPL
  license_file: LICENSE
  summary: Python library for object-oriented analysis of climate model output.
  dev_url: https://github.com/exoclim/aeolus
  doc_url: https://exoclim.github.io/aeolus

extra:
  recipe-maintainers:
    - dennissergeev
