{% set name = "aeolus" %}
{% set version = "24.11.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 7618998e9f5b1926ab4927fecbb908f3c7bc646af95157dca9dd037d0f71c9ec

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - aeolus = aeolus.cli:main

requirements:
  host:
    - python >=3.10
    - pip
    - setuptools >=64
    - setuptools-scm >=8
  run:
    - scitools-iris >=3.10
    - python >=3.10
    - click >=8.1.7
    - click-default-group >=1.2.4
    - python >=3.10
    - cached-property >=1.5.1
    - cartopy >=0.21
    - cf-units >=3.1
    - f90nml
    - iris >=3.9
    - latlon23 >=1.0.7
    - matplotlib-base >=3.6
    - numpy !=1.24.3,>=1.21.0
    - python-stratify

test:
  imports:
    - aeolus
    - aeolus.calc
    - aeolus.const
    - aeolus.coord
    - aeolus.model
    - aeolus.plot
    - aeolus.subset
  commands:
    - pip check
    - aeolus --help
  requires:
    - pip

about:
  home: https://github.com/exoclim/aeolus
  license: LGPL-3.0-only
  license_family: LGPL
  license_file: LICENSE
  summary: Python library for object-oriented analysis of climate model output.
  dev_url: https://github.com/exoclim/aeolus
  doc_url: https://exoclim.github.io/aeolus

extra:
  recipe-maintainers:
    - dennissergeev
